---

- name: installer les paquets apt requis pour l'installation de Yara

  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
   
  with_items:
 
      - automake 
      - libtool 
      - make 
      - gcc 
      - flex 
      - bison
      - libjansson-dev     
      - libmagic-dev 
      - git

- name: Download yara
  get_url:
    url: https://github.com/VirusTotal/yara/archive/v{{ yara_version }}.tar.gz
    dest: /tmp/
    mode: 0440

- name: Extract Yara
  unarchive:
    src: "/tmp/yara-{{ yara_version }}.tar.gz"
    dest: /tmp/ 
    remote_src: yes

- name: yara Bootstrap
  command: ./bootstrap.sh
  args:
    chdir: /tmp/yara-{{ yara_version }}
    
- name: yara Configure
  command: ./configure --enable-cuckoo --enable-magic
  args:
    chdir: /tmp/yara-{{ yara_version }}

- name: yara Make install
  command: make install
  args:
    chdir: /tmp/yara-{{ yara_version }}

- name: download yara-python 
  git:
    repo: 'https://github.com/VirusTotal/yara-python.git'
    dest: /tmp/yara-python


- name: Build yara python module
  command: python setup.py build install
  args:
    chdir: /tmp/yara-python

- name: yara ldconfig
  command: ldconfig
  args:
    chdir: /tmp/yara-python


